package com.knight.easy;

import java.util.ArrayList;
import java.util.List;

/**
 *  Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char[] sChar = s.toCharArray();
        char[] tChar = t.toCharArray();
        List<Character> sList = new ArrayList<Character>();
        List<Character> tList = new ArrayList<Character>();
        for(char temp:sChar){
            sList.add(temp);
        }
        for(char temp:tChar){
            tList.add(temp);
        }
        for(Character c:sList){
            tList.remove(c);
        }
        return tList.get(0);
    }

    public static void main(String[] args) {
        FindTheDifference difference = new FindTheDifference();
        String s = "abcd";
        String t = "abcde";
        System.out.println(difference.findTheDifference(s,t));
    }
}
